# Generated by Django 4.1.6 on 2023-02-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untitled1', '0004_alter_andouuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andouuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
