# Generated by Django 4.1.6 on 2023-02-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untitled1', '0005_alter_andouuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andouuser',
            name='account',
            field=models.FloatField(),
        ),
    ]
